module.exports = {
  rootDir: '.',
  testEnvironment: 'node',
  roots: ['<rootDir>/.build'],
  testMatch: ['<rootDir>/.build/config/env.test.js', '<rootDir>/.build/tests/app.js', '<rootDir>/.build/tests/image-derivative-keys.test.js', '<rootDir>/.build/tests/review-email-template.test.js'],
  modulePaths: ['<rootDir>/.build'],
  collectCoverage: true,
  coverageDirectory: '/tmp/coverage',
  coveragePathIgnorePatterns: ['[\\\\/]test(\\.test)?\\.js$'],
  testTimeout: 30000,
  maxConcurrency: 1,
  forceExit: true,
  detectOpenHandles: true,
  bail: 1,
};